// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPi1vwaAuYD01YZBU5xO2E7-OcD20cnaY',
    appId: '1:91647910264:web:3b915a242ef8031168288d',
    messagingSenderId: '91647910264',
    projectId: 'careroute-77f0c',
    authDomain: 'careroute-77f0c.firebaseapp.com',
    storageBucket: 'careroute-77f0c.firebasestorage.app',
    measurementId: 'G-2WY52NBT3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzsZBcnBWzPoMzRn57iHF-zU2ZX2DOTxQ',
    appId: '1:91647910264:android:9c021fa6cf19769368288d',
    messagingSenderId: '91647910264',
    projectId: 'careroute-77f0c',
    storageBucket: 'careroute-77f0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzf67XiDBVk4bkuAz2GmgmwXdQLqOVqgE',
    appId: '1:91647910264:ios:826a079ed4f5740268288d',
    messagingSenderId: '91647910264',
    projectId: 'careroute-77f0c',
    storageBucket: 'careroute-77f0c.firebasestorage.app',
    iosBundleId: 'com.example.carerouteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzf67XiDBVk4bkuAz2GmgmwXdQLqOVqgE',
    appId: '1:91647910264:ios:826a079ed4f5740268288d',
    messagingSenderId: '91647910264',
    projectId: 'careroute-77f0c',
    storageBucket: 'careroute-77f0c.firebasestorage.app',
    iosBundleId: 'com.example.carerouteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPi1vwaAuYD01YZBU5xO2E7-OcD20cnaY',
    appId: '1:91647910264:web:bc2d2bba6b3acf4068288d',
    messagingSenderId: '91647910264',
    projectId: 'careroute-77f0c',
    authDomain: 'careroute-77f0c.firebaseapp.com',
    storageBucket: 'careroute-77f0c.firebasestorage.app',
    measurementId: 'G-1V0Y0C9LCN',
  );
}
