// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfyjHcTK3u4qJP2UjP0NlkuWLhaVx2NU8',
    appId: '1:645619069323:web:f9505590beb107a9953f8e',
    messagingSenderId: '645619069323',
    projectId: 'careroute-1045b',
    authDomain: 'careroute-1045b.firebaseapp.com',
    storageBucket: 'careroute-1045b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BfQ16clTw9WDrNAGUxQQPKl5XGZ4Io8',
    appId: '1:645619069323:android:62b5644d87dea236953f8e',
    messagingSenderId: '645619069323',
    projectId: 'careroute-1045b',
    storageBucket: 'careroute-1045b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRCkK59WWDIIpym94M070G7NAa8-hH7Qw',
    appId: '1:645619069323:ios:dcd6207531ea2ecb953f8e',
    messagingSenderId: '645619069323',
    projectId: 'careroute-1045b',
    storageBucket: 'careroute-1045b.firebasestorage.app',
    iosBundleId: 'com.example.carerouteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRCkK59WWDIIpym94M070G7NAa8-hH7Qw',
    appId: '1:645619069323:ios:dcd6207531ea2ecb953f8e',
    messagingSenderId: '645619069323',
    projectId: 'careroute-1045b',
    storageBucket: 'careroute-1045b.firebasestorage.app',
    iosBundleId: 'com.example.carerouteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfyjHcTK3u4qJP2UjP0NlkuWLhaVx2NU8',
    appId: '1:645619069323:web:25c35bfa3cda3be6953f8e',
    messagingSenderId: '645619069323',
    projectId: 'careroute-1045b',
    authDomain: 'careroute-1045b.firebaseapp.com',
    storageBucket: 'careroute-1045b.firebasestorage.app',
  );
}